services:
  astro-library:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASTRO_LIBRARY_DATA_DIR: /data
      ASTRO_LIBRARY_LIBRARY_DIR: /library
    volumes:
      - astro-library-data:/data
      - ../example/library:/library:ro

volumes:
  astro-library-data:
